### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [OpenCageData/opencage-qgis-plugin#5]
Please change the plugin homepage link in metadata.txt to reference the repo if you do not have a dedicated page on the website relating to the plugin usage

**Comment by freyfogle** [comment]
Thanks for having a look

We do have a page: https://opencagedata.com/tutorials/geocode-in-qgis
We are just waiting for the plugin to go live so we can show users precisely how to use it.

From the time the plugin is approved to the time the page is live will be max one day.

**Comment by mtmail** [comment]
@NyakudyaA I changed the homepage link to the github repository now. You're right, it contains the best documentation at this point. I also increased the version from 0.1 to 1.0 to indicate it's ready.

**Comment by doublebyte1** [comment]
@NyakudyaA @mtmail done! 👍🏽

**Comment by NyakudyaA** [comment]
LGTM
